name: Biweekly Cron Job

on:
  schedule:
    # Run at 00:00 UTC on Thursday every 2 weeks
    - cron: '0 0 * * 4/2'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-banners:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y git curl unzip

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run script
        run: bun run ./scripts/workflow/update_wishevent.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-update data $(date +'%Y-%m-%d %H:%M:%S')"
          title: "Auto-update: Banner Data Update"
          body: |
            This is an automated pull request to update banner data.
            
            Updates made in this pull request:
            - Ran the update_wishevent.ts script to fetch and process the latest banner data.
            
            Please review the changes and merge if everything looks correct.
          branch: auto-update-banner-data
          base: main
          delete-branch: true
  